export const BASE_URL = `http://190.210.25.141:8000`
// export const BASE_URL = `http://localhost:8000`
export const GRAPH_URL = `${BASE_URL}/graphql`
export const AUTH_URL = 'api-token-auth/'
export const USERS_INDEX = `users/`
export const PERMISSONS_INDEX = `permissons/`
export const USER_PERMISSONS = `userpermissons/`
export const CLIENT_INDEX = 'clientes/'
export const MAPEO_FORM_INDEX = 'mapeosform/'
export const OBSERVACIONES_INDEX = 'observaciones/'
export const SPEECHS_INDEX = 'speechs/'
export const FACTURAS_INDEX = 'facturas/'
export const PAGOS_INDEX = 'pagos/'
export const CONVENIOS_INDEX = 'convenios/'
export const PARAMETROS_INDEX = 'parametros/'
