import {client} from '../plugins/Graphql'
class ClienteRepo {
  index (args) {
    const query = client.query((root) => {
      root.addConnection('allClienteDeudores', args, (clienteDeudor) => {
        clienteDeudor.add('empresa')
        clienteDeudor.add('apenom')
        clienteDeudor.add('tipdoc')
        clienteDeudor.add('domicilio1')
        clienteDeudor.add('telemp1')
        clienteDeudor.add('deudor')
      })
    })
    return client.send(query)
  }
  find (args) {
    const query = client.query((root) => {
      root.addConnection('allClienteDeudores', args, (clienteDeudor) => {
        clienteDeudor.add('empresa')
        clienteDeudor.add('deudor')
        clienteDeudor.add('codemp2')
        clienteDeudor.add('remesa')
        clienteDeudor.add('apenom')
        clienteDeudor.add('domicilio1')
        clienteDeudor.add('compdom1')
        clienteDeudor.add('nro1')
        clienteDeudor.add('piso1')
        clienteDeudor.add('dpto1')
        clienteDeudor.add('ent1')
        clienteDeudor.add('esc1')
        clienteDeudor.add('codpos1')
        clienteDeudor.add('localidad1')
        clienteDeudor.add('provincia1')
        clienteDeudor.add('domicilio2')
        clienteDeudor.add('compdom2')
        clienteDeudor.add('nro2')
        clienteDeudor.add('piso2')
        clienteDeudor.add('dpto2')
        clienteDeudor.add('ent2')
        clienteDeudor.add('esc2')
        clienteDeudor.add('codpos2')
        clienteDeudor.add('localidad2')
        clienteDeudor.add('provincia2')
        clienteDeudor.add('correoe')
        clienteDeudor.add('contacto')
        clienteDeudor.add('tipdoc')
        clienteDeudor.add('cuitdoc')
        clienteDeudor.add('iva')
        clienteDeudor.add('telemp1')
        clienteDeudor.add('telemp2')
        clienteDeudor.add('telemp3')
        clienteDeudor.add('telefono1')
        clienteDeudor.add('telefono2')
        clienteDeudor.add('telefono3')
        clienteDeudor.add('telefono4')
        clienteDeudor.add('telefono5')
        clienteDeudor.add('fAlta')
        clienteDeudor.add('fMora')
        clienteDeudor.add('fCierre')
        clienteDeudor.add('fBaja')
        clienteDeudor.add('fRecepc')
        clienteDeudor.add('fCita')
        clienteDeudor.add('hCita')
        clienteDeudor.add('convenio1')
        clienteDeudor.add('convenio2')
        clienteDeudor.add('carNro')
        clienteDeudor.add('carSec')
        clienteDeudor.add('codsitu')
        clienteDeudor.add('codges')
        clienteDeudor.add('fCamb')
        clienteDeudor.add('fCambg')
        clienteDeudor.add('iduser')
        clienteDeudor.add('deuhist')
        clienteDeudor.add('deuact')
        clienteDeudor.add('tipactu')
        clienteDeudor.add('usercode0')
        clienteDeudor.add('usercode1')
        clienteDeudor.add('usercode2')
        clienteDeudor.add('usercode3')
        clienteDeudor.add('usercode4')
        clienteDeudor.add('usercode5')
        clienteDeudor.add('usercode6')
        clienteDeudor.add('usercode7')
        clienteDeudor.add('usercode8')
        clienteDeudor.add('usercode9')
        clienteDeudor.add('usernum0')
        clienteDeudor.add('usernum1')
        clienteDeudor.add('usernum2')
        clienteDeudor.add('usernum3')
        clienteDeudor.add('usernum4')
        clienteDeudor.add('usernum5')
        clienteDeudor.add('usernum6')
        clienteDeudor.add('usernum7')
        clienteDeudor.add('usernum8')
        clienteDeudor.add('usernum9')
        clienteDeudor.add('userfec1')
        clienteDeudor.add('userfec2')
        clienteDeudor.add('userfec3')
        clienteDeudor.add('userfec4')
        clienteDeudor.add('userfec5')
        clienteDeudor.add('userfec6')
        clienteDeudor.add('filer')
        clienteDeudor.add('iduser1')
        clienteDeudor.add('iduser2')
        clienteDeudor.add('iduser3')
        clienteDeudor.add('iduser4')
        clienteDeudor.add('iduser5')
        clienteDeudor.add('asi')
        clienteDeudor.add('asi1')
        clienteDeudor.add('asi2')
        clienteDeudor.add('asi3')
        clienteDeudor.add('asi4')
        clienteDeudor.add('asi5')
        clienteDeudor.add('politica')
        clienteDeudor.add('comentario')
        clienteDeudor.add('idcontacto')
        clienteDeudor.add('baseneo')
      })
    })
    return client.send(query)
  }
}

export default ClienteRepo
